all:
  vars:
    control_plane_endpoint: 192.168.1.100
    load_balancer_ip_pool:
      - 192.168.10.150/28
metal:
  children:
    masters:
      hosts:
        metal0: {ansible_host: 192.168.10.109, mac: '50:9A:4C:DB:F0:B9', disk: sda, network_interface: eno1}
