all:
  vars:
    control_plane_endpoint: 192.168.1.100
    load_balancer_ip_pool:
      - 192.168.10.150/28
metal:
  children:
    masters:
      hosts:
        metal0: {ansible_host: 192.168.10.109, mac: '34:F6:4B:A6:EC:C6', disk: sda, network_interface: eno1}
